#! /usr/bin/env python

import os

from standard_names import StandardName
from standard_names import (NAMES, OBJECTS, QUANTITIES, OPERATORS)

names = dict (names=NAMES,
              objects=OBJECTS,
              quantities=QUANTITIES,
              operators=OPERATORS,
             )

def main ():
    import argparse

    parser = argparse.ArgumentParser ("Dump known standard names")
    parser.add_argument ('--what', choices=names.keys (),
                        default='names', help='What to dump')
    args = parser.parse_args ()

    print os.linesep.join (names[args.what])

if __name__ == '__main__':
    main ()

