#! /bin/env python

import sys
import re
import urllib

from standard_names import (Collection, FORMATTERS)

as_yaml = FORMATTERS['yaml']
def main ():
    import argparse

    parser = argparse.ArgumentParser ("Scrape standard names from a URL")
    parser.add_argument ('url', metavar='URL', help="URL to scrape")

    args = parser.parse_args ()

    url = urllib.urlopen (args.url)
    text = url.read ()

    words = re.findall (r'\b\w+__\w+', text)
    names = Collection ()
    for word in words:
        names.add (word)

    print as_yaml (names, sorted=True, heading='names')

if __name__ == '__main__':
    main ()
