#! /usr/bin/env python

"""
Example usage:
    snscrape http://csdms.colorado.edu/wiki/CSN_Quantity_Templates \
             http://csdms.colorado.edu/wiki/CSN_Object_Templates \
             http://csdms.colorado.edu/wiki/CSN_Operation_Templates > data/scraped.yaml
"""

import os

from standard_names import FORMATTERS, SCRAPERS, scrape
as_yaml = FORMATTERS['yaml']

DEFAULT_SEARCH = r'\b\w+__\w+'

def main ():
    import argparse

    parser = argparse.ArgumentParser ("Scrape standard names from a file or URL")
    parser.add_argument ('file', nargs='+', metavar='FILE', help="URL or file to scrape")
    parser.add_argument ('--reader', choices=SCRAPERS.keys (),
                         default='url',
                         help="Name of reader ")
    parser.add_argument ('--regex', default=DEFAULT_SEARCH,
                         help='Regular expression describing a standard name (%s)' % DEFAULT_SEARCH)

    args = parser.parse_args ()

    kwds = dict (format=args.reader)
    if args.regex:
        kwds['regex'] = args.regex

    docs = {}
    for file in args.file:
        docs[file] = scrape (file, **kwds)

    documents = []
    for (k, v) in docs.items ():
        documents.append (os.linesep.join ([
            'model name: %s' % k,
            as_yaml (v, sorted=True, heading='exchange items')
        ]))

    docsep = os.linesep + '---' + os.linesep

    print '%YAML 1.2'
    print '---'
    print docsep.join (documents)
    print '...'

if __name__ == '__main__':
    main ()
