name: Format

on: [push, pull_request]

jobs:

  format:

    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4

      - name: Format
        run: |
          pip install black
          black .
